Revised startup shell scripts for Java programs.
The main new feature is that JAVA_HOME is only used if found either in the
environment or in nav.conf.  If not found, the scripts attempt to use a java
executable found on the PATH.  This enables users to configure NAV to run
using an alternative JVM installation on the same server.

* doc/conf/nav.conf
  Comment out the JAVA_HOME setting, and update other comments.

* src/INSTALL
* src/Makefile.in
* src/networkDiscovery/Main-Class
  Bugfixes, networkDiscovery was wrongly referred to as networkTopology in
  several places.

* src/eventEngine/eventEngine.sh.in
* src/getBoksMacs/getBoksMacs.sh.in
* src/getDeviceData/getDeviceData.sh.in
* src/networkDiscovery/networkDiscovery.sh.in
  Refactored for the JAVA_HOME change.  Other improvements include using the
  -jar option to the JVM, and declaring NAV's javalibdir as one of the JVM's
  java.ext.dirs.

diff --git a/src/eventEngine/eventEngine.sh.in b/src/eventEngine/eventEngine.sh.in
--- a/src/eventEngine/eventEngine.sh.in
+++ b/src/eventEngine/eventEngine.sh.in
@@ -14,29 +14,42 @@ if test -z "$JAVA_HOME"; then
     JAVA_HOME=`awk -F= '/JAVA_HOME/ && $1!~/#.*/{gsub("[\t ]", "", $2); print $2}' $NAV_CONF`
 fi
 
+if test -z "$JAVA_HOME"; then
+    JAVA=`which java`
+else
+    JAVA="$JAVA_HOME/bin/java"
+fi
+
+if ! test -x "$JAVA"; then
+    echo "Could not find a suitable Java environment." >&2
+    echo "Maybe you should set the JAVA_HOME variable?" >&2
+    exit 1
+fi
+
 CUR_DIR=${javalibdir}/eventEngine
 LOG_DIR="${localstatedir}/log/eventEngine"
 PIDFILE=${localstatedir}/run/eventEngine.pid
 OUTLOG=${LOG_DIR}/eventEngine-stdout.log
 ERRLOG=${LOG_DIR}/eventEngine-stderr.log
+JVM_OPTS="-Xincgc -Xmx268435456 -Djava.ext.dirs=${javalibdir}"
 
 if test -f $PIDFILE; then
     pidnum=`cat $PIDFILE`
     if (ps -p "${pidnum}" >/dev/null); then
-	echo "eventEngine already running!"
+	echo "eventEngine already running!" >&2
 	exit 1
     fi
 fi
 
 # If error log exists and has content, we rename it before creating a
 # new one
-if [ -s ${ERRLOG} ]; then
+if test -s "${ERRLOG}"; then
     newname="${ERRLOG}.`date +'%Y-%m-%d-%H%M'`.log"
     mv ${ERRLOG} ${newname}
 fi
 
 cd $CUR_DIR
 # Run script
-$JAVA_HOME/bin/java -Xincgc -Xmx268435456 -cp "eventEngine.jar:$CLASSPATH" eventEngine $1 >> ${OUTLOG} 2> ${ERRLOG} &
+$JAVA $JVM_OPTS -jar eventEngine.jar $1 >> ${OUTLOG} 2> ${ERRLOG} < /dev/null & 
 pidno="$!"
 echo $pidno > $PIDFILE
diff --git a/src/getBoksMacs/getBoksMacs.sh.in b/src/getBoksMacs/getBoksMacs.sh.in
--- a/src/getBoksMacs/getBoksMacs.sh.in
+++ b/src/getBoksMacs/getBoksMacs.sh.in
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
-# Relativt komplisert script på grunn av at java-prosessen kan henge seg opp,
-# og da må den drepes - men kun hvis den har gjort seg ferdig, som indikert
-# med job-finished filen.
+# This script is relatively complicated.  The getBoksMacs process sometimes
+# hangs, and instead of fixing the bug that causes this problem, an elaborate
+# hack to kill the process has been written instead.  getBoksMacs indicates
+# that its work is done by creating the $JOB_FINISHED file.
 
 prefix=@prefix@
 exec_prefix=@exec_prefix@
@@ -13,18 +14,31 @@ javalibdir=@javalibdir@
 
 NAV_CONF="${sysconfdir}/nav.conf"
 
-if [ "$JAVA_HOME" == "" ]; then
-	JAVA_HOME=`awk -F= '/JAVA_HOME/ && $1!~/#.*/{gsub("[\t ]", "", $2); print $2}' $NAV_CONF`
+if test -z "$JAVA_HOME"; then 
+    JAVA_HOME=`awk -F= '/JAVA_HOME/ && $1!~/#.*/{gsub("[\t ]", "", $2); print $2}' $NAV_CONF`
+fi
+
+if test -z "$JAVA_HOME"; then
+    JAVA=`which java`
+else
+    JAVA="$JAVA_HOME/bin/java"
+fi
+
+if ! test -x "$JAVA"; then
+    echo "Could not find a suitable Java environment." >&2
+    echo "Maybe you should set the JAVA_HOME variable?" >&2
+    exit 1
 fi
 
 CUR_DIR=${javalibdir}/getBoksMacs
 LOG_DIR="${localstatedir}/log"
 PIDFILE=${localstatedir}/run/getBoksMacs.pid
 JOB_FINISHED=${localstatedir}/run/boksmacs-finished.flag
+JVM_OPTS="-Xmx268435456 -Djava.ext.dirs=${javalibdir}"
 
 
 getpid() {
-    if [ -f $PIDFILE ]; then
+    if test -f "$PIDFILE"; then
 	local pidnum=`cat $PIDFILE`
 	if (ps -p "${pidnum}" >/dev/null); then
 	    echo $pidnum
@@ -32,30 +46,30 @@ getpid() {
     fi
 }
 
-if [ -z `getpid` ] || [ -f $JOB_FINISHED ]; then
+if test -z `getpid` || test -f "$JOB_FINISHED"; then
     cd $CUR_DIR
-    if [ -f $JOB_FINISHED ]; then
+    if test -f "$JOB_FINISHED"; then
         # Must kill old script
 	kill -9 $pidnum
-	rm -f $JOB_FINISHED
+	rm -f "$JOB_FINISHED"
 	sleep 2
     fi
 
     # Check again that getBoksMacs is not already running
-    if [ -z `getpid` ]; then
-        # Now run script
-	$JAVA_HOME/bin/java -Xmx268435456 -cp "getBoksMacs.jar:$CLASSPATH" getBoksMacs $1 >> "$LOG_DIR/getBoksMacs.log" &
+    if test -z `getpid`; then
+        # Now run the camlogger
+	$JAVA $JVM_OPTS -jar getBoksMacs.jar $1 >> "$LOG_DIR/getBoksMacs.log" &
 	pidno="$!"
 	echo $pidno >$PIDFILE
 	wait $pidno
-	if [ -f $JOB_FINISHED ]; then
-	    rm -f $JOB_FINISHED
+	if test -f "$JOB_FINISHED"; then
+	    rm -f "$JOB_FINISHED"
 	fi
 	rm $PIDFILE
     else
-	echo "ERROR, kill -9 of previous getBoksMacs failed!"
+	echo "ERROR, kill -9 of previous getBoksMacs failed!" >&2
+	exit 1
     fi
 else
-    # echo "getBoksMacsMulti already running (and not finished)"
-    echo -n ""
+    echo "Previous instance of getBoksMacs is still not finished" >&2
 fi
diff --git a/src/networkDiscovery/networkDiscovery.sh.in b/src/networkDiscovery/networkDiscovery.sh.in
--- a/src/networkDiscovery/networkDiscovery.sh.in
+++ b/src/networkDiscovery/networkDiscovery.sh.in
@@ -14,18 +14,31 @@ if test -z "$JAVA_HOME"; then
     JAVA_HOME=`awk -F= '/JAVA_HOME/ && $1!~/#.*/{gsub("[\t ]", "", $2); print $2}' $NAV_CONF`
 fi
 
+if test -z "$JAVA_HOME"; then
+    JAVA=`which java`
+else
+    JAVA="$JAVA_HOME/bin/java"
+fi
+
+if ! test -x "$JAVA"; then
+    echo "Could not find a suitable Java environment." >&2
+    echo "Maybe you should set the JAVA_HOME variable?" >&2
+    exit 1
+fi
+
 CUR_DIR=${javalibdir}/networkDiscovery
 LOG_DIR="${localstatedir}/log/networkDiscovery"
 OUTLOG=${LOG_DIR}/networkDiscovery-$1.html
 ERRLOG=${LOG_DIR}/networkDiscovery-stderr.log
+JVM_OPTS="-Xmx268435456 -Djava.ext.dirs=${javalibdir}"
 
 # If error log exists and has content, we rename it before creating a
 # new one
-if [ -s ${ERRLOG} ]; then
+if test -s ${ERRLOG}; then
     newname="${ERRLOG}.`date +'%Y-%m-%d-%H%M'`.log"
     mv ${ERRLOG} ${newname}
 fi
 
 cd $CUR_DIR
-# Run script
-$JAVA_HOME/bin/java -Xmx268435456 -cp "networkDiscovery.jar:$CLASSPATH" networkDiscovery $1 $2 > ${OUTLOG} 2> ${ERRLOG}
+# Run program
+$JAVA $JVM_OPTS -jar networkDiscovery.jar $* > ${OUTLOG} 2> ${ERRLOG}
